#!/usr/bin/env bash
#transfers a file from our client to a server:
#Accepts 4 parameters indicated on the usage
#Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
#Steps: SSH ubuntu@52.87.254.224 i /~ 'ls ~/'  # to view files in our web server
#	./0-transfer_file page.html 52.87.254.224 ubuntu /~	# execute this file to transfer page.html
#	SSH ubuntu@52.87.254.224 i /~ 'ls ~/'  # to view page.html file in our web server
#scp must transfer the file to the user home directory ~/
#Strict host key checking must be disabled when using scp
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
